# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQt8jNFfleRmoRh4SpviZtVH6UsNqWbG
"""

#Question-1
#Assign a empty list in l
l = []
#running for loop between 2000 to 3201 through the help of range function 
for i in range(2000,3201):
  #checking the condition
  if (i%7==0) and (i%5==0):
    #convert intger to string and adding the number
    l.append(str(i))
#print the number with comma-separated in to l
print(',',(l))

#Question-2
#first Name inupt for user
a = input("Please Enter First Name ")
#second Name inupt for user
b = input("Please Enter Last Name ")
#combine both name
Name = (a + " " + b)
#split the name
a=Name.split()
#reverse the string
a.reverse()
#join the reverse string
finalresult = " ".join(a)
print(finalresult)

#Quesion-3
pi = 2.4
r= 5.0
V= 4.0/3.0*pi* r**3
print('The volume of the sphere is:',V)

#Question-4
#Input for user to Enter the number
number =  input("Pleas Enter some number")
#Creat a list
list = number.split(",")
#print list
print (list)

#Question-5
#Assign a number for loop
n = 5
#running for loop in the range of 0to5
for  i in range(0,n):
  for j in range(0,i+1):
    #print * accoring to the loop value
    print("*",end= " ")
  print("\r")
b = 3
for  i in range(b,-1,-1):
  for j in range(0,i+1):
    print("*",end= " ")
  print("\r")

#Question-6
"User has to Enter the word"
A = input("please Enter the word ")
#through the help of indexing we change the word to reverses.
B = A[::-1]
print(B)

#Question-7
#Assign full sentance into one variable
sen = "WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a SOVEREIGN, SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC and to secure to all its citizens"
#split the sentance
ssplit = sen.split()
type(ssplit)
#Running a  for loop to identify the required word
for i in ssplit:
  if i =="SOVEREIGN,":
    l = ssplit.index(i)
    #replace the old word to new word
    ssplit[l] ="SOVEREIGN,!"
#Change list to string
def listToString(s): 
  str1 = " "
  return(str1.join(s))
s = ssplit
print(listToString(s))

